FROM php:8.2.1-apache
WORKDIR /var/www/html
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli && docker-php-ext-install pdo pdo_mysql
RUN apt-get update -y && apt-get install -y sendmail libpng-dev
RUN docker-php-ext-install gd
COPY applications/jcouve/public /var/www/html 
RUN a2enmod rewrite